import { Link } from "react-router-dom";

const TEAL = "#0d9488";
const GRAY_TEXT = "#6b7280";
const DARK = "#111827";
const DIVIDER = "1px solid #e5e7eb";

export default function Terms() {
  return (
    <div style={{ fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif", background: "#fff", color: DARK, minHeight: "100vh" }}>
      <nav style={{ background: "#fff", borderBottom: DIVIDER, padding: "0 48px", display: "flex", alignItems: "center", justifyContent: "space-between", height: 60 }}>
        <Link to="/" style={{ display: "flex", alignItems: "center", gap: 8, textDecoration: "none" }}>
          <div style={{ width: 30, height: 30, background: TEAL, borderRadius: 7, display: "flex", alignItems: "center", justifyContent: "center" }}>
            <span style={{ color: "#fff", fontSize: 15, fontWeight: 700 }}>W</span>
          </div>
          <span style={{ fontWeight: 700, fontSize: 15, color: DARK }}>WorkforceAutomated</span>
        </Link>
        <Link to="/login" style={{ color: GRAY_TEXT, fontSize: 14, textDecoration: "none" }}>Sign in</Link>
      </nav>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "64px 48px" }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, color: DARK, margin: "0 0 8px" }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: GRAY_TEXT, margin: "0 0 48px" }}>Last updated: March 19, 2026</p>

        <div style={{ borderTop: DIVIDER }}>
          {[
            {
              title: "1. Acceptance of Terms",
              body: "By creating an account or using WorkforceAutomated, you agree to these Terms of Service. If you do not agree, do not use the platform. These terms apply to all users, including free trial users.",
            },
            {
              title: "2. Service Description",
              body: "WorkforceAutomated is an enterprise AI Workforce Operating System that allows users to configure, deploy, and manage AI agents for business process automation. The platform uses OpenAI's language models to process tasks. Agent outputs are AI-generated and should be reviewed by qualified humans before acting on them.",
            },
            {
              title: "3. Account Responsibilities",
              body: "You are responsible for maintaining the security of your account credentials. You must not share your account with others. You must not use the platform for illegal purposes. You must not attempt to reverse-engineer, scrape, or abuse the platform's APIs. You are responsible for all activity that occurs under your account.",
            },
            {
              title: "4. AI-Generated Content",
              body: "Agent outputs are generated by AI models and may contain errors, inaccuracies, or omissions. WorkforceAutomated does not guarantee the accuracy of AI-generated content. You are responsible for reviewing and validating all agent outputs before using them for business decisions. Do not use agent outputs as legal, medical, or financial advice without independent professional review.",
            },
            {
              title: "5. Subscription and Billing",
              body: "Paid plans are billed monthly or annually via Stripe. You may cancel at any time; cancellation takes effect at the end of the current billing period. Refunds are not provided for partial billing periods. Plan limits (agent count, execution volume) are enforced automatically. Exceeding limits requires an upgrade.",
            },
            {
              title: "6. Data Ownership",
              body: "You own your data. WorkforceAutomated does not claim ownership of your agent configurations, inputs, or outputs. We will not use your data to train AI models without your explicit consent. Upon account deletion, your data is removed within 90 days.",
            },
            {
              title: "7. Limitation of Liability",
              body: "WorkforceAutomated is provided 'as is' without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability is limited to the amount you paid in the 12 months preceding the claim.",
            },
            {
              title: "8. Termination",
              body: "We may suspend or terminate accounts that violate these terms, engage in abuse, or pose a security risk. You may terminate your account at any time from the Billing page.",
            },
            {
              title: "9. Changes to Terms",
              body: "We may update these terms. We will notify you by email at least 14 days before material changes take effect. Continued use after the effective date constitutes acceptance.",
            },
            {
              title: "10. Contact",
              body: "For questions about these terms, contact: legal@workforceautomated.com",
            },
          ].map((section) => (
            <div key={section.title} style={{ padding: "28px 0", borderBottom: DIVIDER }}>
              <h2 style={{ fontSize: 16, fontWeight: 700, color: DARK, margin: "0 0 10px" }}>{section.title}</h2>
              <p style={{ fontSize: 14, color: "#374151", lineHeight: 1.75, margin: 0 }}>{section.body}</p>
            </div>
          ))}
        </div>
      </div>

      <footer style={{ background: DARK, padding: "32px 48px", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 16 }}>
        <span style={{ color: "#9ca3af", fontSize: 13 }}>WorkforceAutomated © 2026</span>
        <div style={{ display: "flex", gap: 24 }}>
          <a href="mailto:contact@workforceautomated.com" style={{ color: "#9ca3af", fontSize: 12, textDecoration: "none" }}>contact@workforceautomated.com</a>
          <Link to="/privacy" style={{ color: "#9ca3af", fontSize: 13, textDecoration: "none" }}>Privacy</Link>
          <Link to="/terms" style={{ color: "#9ca3af", fontSize: 13, textDecoration: "none" }}>Terms</Link>
          <Link to="/security-overview" style={{ color: "#9ca3af", fontSize: 13, textDecoration: "none" }}>Security</Link>
        </div>
      </footer>
    </div>
  );
}
